# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x02pb\"\x19\n\nSumRequest\x12\x0b\n\x03num\x18\x01 \x01(\x03\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\x32\x37\n\tCalculate\x12*\n\x03Sum\x12\x0e.pb.SumRequest\x1a\x0f.pb.SumResponse\"\x00(\x01\x42\x07Z\x05./;pdb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005./;pd'
  _SUMREQUEST._serialized_start=19
  _SUMREQUEST._serialized_end=44
  _SUMRESPONSE._serialized_start=46
  _SUMRESPONSE._serialized_end=75
  _CALCULATE._serialized_start=77
  _CALCULATE._serialized_end=132
# @@protoc_insertion_point(module_scope)
