# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.pb
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nexample.pb\x12\x07\x65xample\"\x8a\x01\n\x07Teacher\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0b\n\x03\x41ge\x18\x02 \x01(\x05\x12%\n\x05level\x18\x03 \x01(\x0e\x32\x16.example.Teacher.Level\x12\x0e\n\x06\x43ourse\x18\x04 \x01(\t\"-\n\x05Level\x12\x0c\n\x08LECTURER\x10\x00\x12\n\n\x06\x44OCTOR\x10\x01\x12\n\n\x06MASTER\x10\x02\x42\x0bZ\t.;exampleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.pb_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\t.;example'
  _TEACHER._serialized_start=24
  _TEACHER._serialized_end=162
  _TEACHER_LEVEL._serialized_start=117
  _TEACHER_LEVEL._serialized_end=162
# @@protoc_insertion_point(module_scope)
